eureka:
  instance:
    preferIpAddress: true
    ip-address: 114.67.94.23
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
