server:
  port: 8761

eureka:
  instance:
    hostname: 39.97.183.184
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://114.67.94.23:${server.port}/eureka/
