eureka:
  client:
    serviceUrl:
      defaultZone: http://114.67.94.23:8761/eureka/
  instance:
      ip-address: 39.97.183.184
      preferIpAddress: true

server:
  port: 8763
spring:
  application:
    name: service-hi
